# Dockerfile base for python version 3.12

FROM python:3.10-alpine

ONBUILD RUN apk add --no-cache bash

ONBUILD COPY . /app

ONBUILD WORKDIR /app

ONBUILD RUN pip install --upgrade pip

ONBUILD RUN pip install -r requirements.txt

ONBUILD CMD ["python", "-m", "app"]