# Dockerfile standalone for python image
FROM python:3.10-alpine

RUN apk add --no-cache bash

COPY . /app

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["python", "-m", "app"]