- name: Launching Jenkins in a docker compose
  hosts: default
  become: true
  gather_facts: no

  tasks:
    - name: Updating packages
      apt:
        update_cache: yes

    - name: Installing all dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Adding Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Adding link to repository of Docker binary 
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
        state: present

    - name: Installing Docker
      apt:
        name: docker-ce
        state: latest

    - name: Downloading latest version of Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      ignore_errors: true

    - name: checking Docker Compose install version
      command: docker-compose --version


    - name: creating whanos directory on the vm
      file:
        path: /home/ubuntu/whanos
        state: directory
        mode: '0755'

    - name: Copying docker-compose in whanos directory
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /home/ubuntu/whanos/
        mode: '0664'

    - name: Copying Dockerfile in whanos directory
      ansible.builtin.copy:
        src: Dockerfile
        dest: /home/ubuntu/whanos/
        mode: '0664'

    - name: Copying  jenkins files in whanos directory
      ansible.builtin.copy:
        src: jenkins
        dest: /home/ubuntu/whanos/
        mode: '0664'

    - name: Copying dockers images in whanos directory
      ansible.builtin.copy:
        src: images
        dest: /home/ubuntu/whanos/
        mode: '0664'

    - name: Copying env plugin in whanos directory
      ansible.builtin.copy:
        src: .env
        dest: /home/ubuntu/whanos/
        mode: '0664'

    - name: Launching Docker Compose
      ansible.builtin.shell:
        cmd: docker-compose up -d
        chdir: /home/ubuntu/whanos