FROM alpine:3.14

ONBUILD RUN apk add --no-cache build-base wget ncurses-dev git

ONBUILD WORKDIR /app

ONBUILD RUN git clone https://codeberg.org/catseye/Befunge-93.git \
    && cd Befunge-93 \
    && make \
    && cp bin/bef ../ \
    && cd .. \
    && rm -rf Befunge-93

ONBUILD COPY . /app

ONBUILD CMD ["./bef", "-o", "app", "main.bf"]