# Dockerfile.standalone 

FROM alpine:3.14

RUN apk add --no-cache build-base wget ncurses-dev git

WORKDIR /app

RUN git clone https://codeberg.org/catseye/Befunge-93.git \
    && cd Befunge-93 \
    && make \
    && cp bin/bef ../ \
    && cd .. \
    && rm -rf Befunge-93 

COPY . /app

CMD ["./bef", "-o", "app", "main.bf"]