# Dockerfile.standalone JAVA

FROM alpine:3.14

RUN apk add --no-cache build-base wget ncurses-dev git

WORKDIR /app

RUN git clone https://codeberg.org/catseye/Befunge-93.git \
    && cd Befunge-93 \
    && make \
    && cp bin/bef /usr/local/bin \
    && cd .. \
    && rm -rf Befunge-93 

COPY /app/main.bf .

RUN bef -o app app.bf
CMD [ "./app" ]